# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        carre:
            quality: 85
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound

        echelle:
            quality: 85
            filters:
                scale:
                    dim: [500, 400]

        produit:
            quality: 85
            filters:
                upscale:
                    dim: [ 800, 500 ]
                thumbnail:
                    size: [ 800, 500 ]
                    mode: outbound
